# Site settings
description: A blog containing recent projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scaperoth.github.io" # the base hostname & protocol for your site

# User settings
username: scaperoth
user_description:
user_title: Matt Scaperoth
email: scaperoth@gmail.com
github_username: scaperoth
disqus_username: scaperoth
google_analytics: "UA-67559082-1"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

#pagination
gems: [jekyll-paginate]
paginate: 4
paginate_path: "/posts/page:num/"

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
